export const desktopBridgeChannels = {
  getContext: 'desktop:get-context',
  listConversations: 'desktop:list-conversations',
  getProviderStatus: 'desktop:get-provider-status',
  getProviderCredentialStatus: 'desktop:get-provider-credential-status',
  saveProviderAuth: 'desktop:save-provider-auth',
  startProviderOauth: 'desktop:start-provider-oauth',
  clearProviderAuth: 'desktop:clear-provider-auth',
  exportData: 'desktop:export-data',
  importData: 'desktop:import-data',
  getSettings: 'desktop:get-settings',
  saveSettings: 'desktop:save-settings',
  getConversation: 'desktop:get-conversation',
  startRun: 'desktop:start-run',
  resumeRun: 'desktop:resume-run',
  cancelRun: 'desktop:cancel-run',
  resolveApproval: 'desktop:resolve-approval',
  openExternalUrl: 'desktop:open-external-url',
  runEvent: 'desktop:run-event',
} as const
